// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplyMessageType } from "./ReplyMessageType";

export type MessageReply = { message_id: string, user_id: String, username: string | null, content_preview: string, message_type: ReplyMessageType, };
