// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomMember } from "./RoomMember";

export type RoomMembersResponse = { members: Array<RoomMember>, };
