// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageDeleteEvent } from "./MessageDeleteEvent";
import type { MessageEditEvent } from "./MessageEditEvent";
import type { ReactionEvent } from "./ReactionEvent";
import type { ReactionRemoveEvent } from "./ReactionRemoveEvent";
import type { TextMessageEvent } from "./TextMessageEvent";
import type { UserJoinEvent } from "./UserJoinEvent";
import type { UserLeaveEvent } from "./UserLeaveEvent";

export type RoomEventData = { "Message": TextMessageEvent } | { "MessageEdit": MessageEditEvent } | { "MessageDelete": MessageDeleteEvent } | { "Reaction": ReactionEvent } | { "ReactionRemove": ReactionRemoveEvent } | { "UserJoin": UserJoinEvent } | { "UserLeave": UserLeaveEvent };
