// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomListItem } from "./RoomListItem";

export type RoomListResponse = { rooms: Array<RoomListItem>, };
