// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReactionEvent } from "./ReactionEvent";
import type { TextMessageEvent } from "./TextMessageEvent";

export type RoomEventData = { "Message": TextMessageEvent } | { "Reaction": ReactionEvent };
