// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomEventData } from "./RoomEventData";

export type RoomEvent = { id: string, from: String, timestamp: string, data: RoomEventData, };
