// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageReply } from "./MessageReply";

export type TextMessageEvent = { content: string, edited: boolean, deleted: boolean, reply_to: MessageReply | null, };
